- hosts: sensu 
  become: true
  tasks: 
   - name: download Erlang 
     get_url:
       url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
       dest: /root/troll	      
       mode: 0755

   - name: install Erlang 
     command: dpkg -i erlang-solutions_1.0_all.deb
        
   - name: Erlang key repo
     command: wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | sudo apt-key add -

   - name: update erlang
     apt: 
     update_cache: yes

   - name: install socat
     apt: name=socat state=present

   - name: install erlang-nox
     apt: name=erlang-nox state=present

   - name: download RabbitMQ
     get_url: 
       url: http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.10/rabbitmq-server_3.6.10-1_all.deb

   - name: install Rabbit;Q
     command: dpkg -i rabbitmq-server_3.6.10-1_all.deb

   - name: update RabbitMQ
     apt:
     update_cache: yes

   - name: install RabbitMQ server
     apt: name=rabbitmq-server state=present

   - name: start rabbit MQ
     service: 
       name: rabbitmq-server
       state: started

   - name: enable rabbitmq
     service: 
       name: rabbitmq-server
       enabled: yes

   - name: create vhost for sensu
     command: rabbitmqctl add_vhost /sensu

   - name: create user for sensu
     command: rabbitmqctl add_user sensu sensupwd

   - name: set permissions
     command: rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"

   - name: add GPG key
     command: wget -O- https://sensu.global.ssl.fastly.net/apt/pubkey.gpg | sudo apt-key add -

   - name: add sensu repository
     command: echo "deb https://sensu.global.ssl.fastly.net/apt sensu main" >> /etc/apt/sources.list.d/sensu.list

   - name: update sensu
     apt: 
     update_cache: yes
 
   - name: move rabbitmq json file
     command: mv /root/troll/rabbitmq.json /etc/sensu/conf.d/rabbitmq.json

   - name: move redis json file
     command: mv /root/troll/redis.json /etc/sensu/conf.d/redis.json

   - name: move api json file
     command: mv /root/troll/api.json /etc/sensu/conf.d/api.json

   - name: add public key for Uchiwa
     command: wget -O- https://sensu.global.ssl.fastly.net/apt/pubkey.gpg | sudo apt-key add -

   - name: add uchiwa repository
     command: echo "deb https://sensu.global.ssl.fastly.net/apt sensu main" >> /etc/apt/sources.list.d/uchiwa.list

   - name: update uchiwa repo
     apt: 
     update_cache: yes

   - name: install uchiwa
     apt: name=uchiwa state=present

   - name: move uchiwa json file
     command: mv /root/troll/uchiwa.json /etc/sensu/conf.d/uchiwa.son

   - name: restart sensu server
     service:
       name: sensu-server
       state: restarted

   - name: restart sensu api
     service: 
       name: sensu-api
       state: restarted

   - name: restart sensu client
     service:
       name: sensu-client
       state: restarted

   - name: restart uchiwa
     service:
       name: uchiwa
       state: restarted

   - name: move client json file
     command: mv /root/troll/client.json /etc/sensu/conf.d/client.json

   - name: restart client
     service:
       name: sensu-client
       state: restart

